/* eslint-disable @next/next/no-img-element -- private signed Storage URLs are intentionally rendered directly */
import { ArrowLeft, Download, ExternalLink, Mail, Phone, Star } from 'lucide-react';
import Link from 'next/link';
import { notFound } from 'next/navigation';

import { ContactDeletePanel } from '@/components/contact-delete-panel';
import { contactName, getWebContact, type WebContact } from '@/lib/contacts';
import { requireWebUser } from '@/lib/supabase/server';

import { saveContact, toggleFavoriteForm, uploadContactPhoto } from '../../actions';

type Params = Promise<{ id: string }>;
type Query = Promise<{ saved?: string; photo?: string }>;

const empty = (id: string): WebContact => ({ id, display_name: '', first_name: '', middle_name: '', last_name: '', company: '', job_title: '', department: '', primary_email: '', primary_phone: '', website: '', address_line_1: '', address_line_2: '', city: '', state_region: '', postal_code: '', country: '', notes: '', raw_extracted_text: '', contact_photo_path: null, is_favorite: false, created_at: '', updated_at: '', card_emails: [], card_phone_numbers: [], card_websites: [], card_addresses: [], card_images: [], card_tags: [], avatar_url: null });

export default async function ContactDetailPage({ params, searchParams }: { params: Params; searchParams: Query }) {
  const { id } = await params; const query = await searchParams; const isNew = id === 'new';
  const contact = isNew ? empty(id) : await getWebContact(id); if (!contact) notFound();
  const { supabase } = await requireWebUser();
  const imageUrls = Object.fromEntries(await Promise.all(contact.card_images.map(async (image) => { const { data } = await supabase.storage.from('card-images').createSignedUrl(image.storage_path, 3600); return [image.side, data?.signedUrl ?? null]; })));
  const tags = contact.card_tags.map((item) => item.tags?.name).filter(Boolean).join(', ');
  const favoriteAction = toggleFavoriteForm.bind(null);
  return <section className="workspace-page detail-page">
    <div className="detail-back"><Link href="/app/contacts"><ArrowLeft size={18} />Back to contacts</Link></div>
    <header className="detail-hero"><div className="large-avatar">{contact.avatar_url ? <img alt="" src={contact.avatar_url} /> : contactName(contact).slice(0, 1).toUpperCase()}</div><div><p className="eyebrow">{isNew ? 'NEW CONTACT' : 'CONTACT PROFILE'}</p><h1>{isNew ? 'Add a contact' : contactName(contact)}</h1><p>{[contact.job_title, contact.company].filter(Boolean).join(' · ') || 'Card Nest contact'}</p></div>{!isNew ? <div className="detail-actions">{contact.primary_phone ? <a className="icon-action" href={`tel:${contact.primary_phone}`}><Phone />Call</a> : null}{contact.primary_email ? <a className="icon-action" href={`mailto:${contact.primary_email}`}><Mail />Email</a> : null}{contact.website ? <a className="icon-action" href={/^https?:/u.test(contact.website) ? contact.website : `https://${contact.website}`} rel="noreferrer" target="_blank"><ExternalLink />Website</a> : null}<a className="icon-action" href={`/api/app/export?format=vcard&ids=${contact.id}`}><Download />vCard</a><form action={favoriteAction}><input name="id" type="hidden" value={contact.id} /><input name="favorite" type="hidden" value={String(!contact.is_favorite)} /><button className="icon-action"><Star fill={contact.is_favorite ? 'currentColor' : 'none'} />Favorite</button></form></div> : null}</header>
    {query.saved ? <div className="notice success" role="status">Contact saved to your Card Nest cloud library.</div> : null}{query.photo === 'saved' ? <div className="notice success">Contact photo updated.</div> : null}{query.photo === 'invalid' ? <div className="notice">Choose a valid image smaller than 8 MB.</div> : null}
    <div className="detail-grid"><form action={saveContact} className="panel contact-form"><input name="id" type="hidden" value={contact.id} /><div className="panel-heading"><div><p className="eyebrow">CONTACT DETAILS</p><h2>{isNew ? 'Create contact' : 'Edit contact'}</h2></div><button className="button button-primary">Save contact</button></div>
      <div className="field-grid"><label className="span-2">Display name<input name="displayName" defaultValue={contact.display_name ?? ''} /></label><label>First name<input name="firstName" defaultValue={contact.first_name ?? ''} /></label><label>Middle name<input name="middleName" defaultValue={contact.middle_name ?? ''} /></label><label>Last name<input name="lastName" defaultValue={contact.last_name ?? ''} /></label><label>Company<input name="company" defaultValue={contact.company ?? ''} /></label><label>Job title<input name="jobTitle" defaultValue={contact.job_title ?? ''} /></label><label>Department<input name="department" defaultValue={contact.department ?? ''} /></label>
      <label className="span-2">Email addresses <small>One per line; the first is primary</small><textarea name="emails" defaultValue={contact.card_emails.length ? contact.card_emails.map((item) => item.email).join('\n') : contact.primary_email ?? ''} rows={3} /></label><label className="span-2">Phone numbers <small>One per line; the first is primary</small><textarea name="phones" defaultValue={contact.card_phone_numbers.length ? contact.card_phone_numbers.map((item) => item.phone_number).join('\n') : contact.primary_phone ?? ''} rows={3} /></label><label className="span-2">Websites <small>One per line</small><textarea name="websites" defaultValue={contact.card_websites.length ? contact.card_websites.map((item) => item.url).join('\n') : contact.website ?? ''} rows={2} /></label>
      <label className="span-2">Address line 1<input name="addressLine1" defaultValue={contact.address_line_1 ?? ''} /></label><label className="span-2">Address line 2<input name="addressLine2" defaultValue={contact.address_line_2 ?? ''} /></label><label>City<input name="city" defaultValue={contact.city ?? ''} /></label><label>State / region<input name="stateRegion" defaultValue={contact.state_region ?? ''} /></label><label>Postal code<input name="postalCode" defaultValue={contact.postal_code ?? ''} /></label><label>Country<input name="country" defaultValue={contact.country ?? ''} /></label><label className="span-2">Tags <small>Comma separated</small><input name="tags" defaultValue={tags} /></label><label className="span-2">Notes<textarea name="notes" defaultValue={contact.notes ?? ''} rows={4} /></label><label className="span-2">Original transcription<textarea name="rawText" defaultValue={contact.raw_extracted_text ?? ''} rows={5} /></label></div>
    </form>
    <aside className="detail-aside">{!isNew ? <form action={uploadContactPhoto} className="panel form-stack"><p className="eyebrow">CONTACT PHOTO</p><h2>Photo or Gravatar</h2><p className="muted">A private uploaded photo takes priority over the email-based Gravatar fallback.</p><input name="id" type="hidden" value={contact.id} /><label>Upload photo<input accept="image/*" name="photo" required type="file" /></label><button className="button button-secondary">Upload photo</button></form> : null}{Object.values(imageUrls).some(Boolean) ? <section className="panel"><p className="eyebrow">ORIGINAL CARD</p><h2>Saved images</h2><div className="card-image-stack">{imageUrls.front ? <img alt="Front of business card" src={imageUrls.front} /> : null}{imageUrls.back ? <img alt="Back of business card" src={imageUrls.back} /> : null}</div></section> : null}{!isNew ? <ContactDeletePanel contactId={contact.id} contactName={contactName(contact)} /> : null}</aside></div>
  </section>;
}
